version: '3.3'

services:
  database:
    image: postgres:alpine3.15
    container_name: postgress_db
    restart: always
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_CONTAINER_PORT
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRESS_DB_NAME
      - PGDATA=$POSTGRES_DATA_DIR
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend

  server:
    depends_on:
      - database
    build: ./server
    restart: always
    ports:
      - $NODE_LOCAL_PORT:$NODE_CONTAINER_PORT
    env_file:
      - ./.env
    volumes:
      - ./server:/usr/server
    networks:
      - backend
      - frontend


volumes:
  db:

networks:
  backend:
  frontend:
    