version: '3.3'

services:
  database:
    image: postgres:alpine3.15
    container_name: postgress_db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=database
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db:

networks:
  backend:
  frontend:
    