version: '3.3'

services:
  postgres:
    container_name: postgres-db
    image: postgres
    restart: always
    env_file:
     - ./.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db:/data/postgres
    networks:
      - backend

  server:
    depends_on:
      - postgres
    build: ./server
    restart: always
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./.env
    volumes:
      - ./server:/usr/server
    networks:
      - backend
      - frontend
    
  client:
    build: ./client
    depends_on:
      - server
    restart: always
    ports:
      - ${LOCAL_REACT_PORT}:${CONTAINER_REACT_PORT}
    volumes:
      - ./client:/app
    networks:
      - frontend

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db:

networks:
  backend:
  frontend:
    